version: '3'

services:
  # MongoDB service
  mongo:
    image: mongo:latest
    container_name: kamilla-database
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: yten
      MONGO_INITDB_ROOT_PASSWORD: yten
      MONGO_INITDB_DATABASE: kamilla
    volumes:
      - mongo-data:/data/db

  # Mongo Express service
  mongo-express:
    image: mongo-express:latest
    container_name: kamilla-database-express-container

    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: yten
      ME_CONFIG_MONGODB_ADMINPASSWORD: yten
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: yten
      ME_CONFIG_BASICAUTH_PASSWORD: yten
    depends_on:
      - mongo

volumes:
  mongo-data:
