import "./globals.css";
import {Link} from "@/src/common/Link";
import {Roboto} from 'next/font/google'
import classNames from "classnames";

const montserrat = Roboto({
  weight: ["400", "700"],
  subsets: ["cyrillic"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  return (
    <html lang="ru">
    <body
      className={classNames("flex flex-col min-h-screen", montserrat.className)}
    >
    <header className="bg-[#ADBFAD] py-5">
      <div className="container mx-auto flex items-center justify-between">
        <div className="text-white text-3xl font-[Suluskin]">Твой Логотип</div>

        <nav className="space-x-6">
          <Link href="/">Главная</Link>
          <Link href="/about" className="text-white hover:text-[#333333]">О нас</Link>
          <Link href="#" className="text-white hover:text-[#333333]">Контакты</Link>
        </nav>

        <div className="flex items-center space-x-4">
          <a href="https://wa.me/1234567890"
             target="_blank">
            <img src="/wp.svg" alt="" className={"w-7"}/>
          </a>

          <a href="https://www.instagram.com"
             target="_blank">
            <img src="/instagram.svg" alt="" className={"w-7"}/>
          </a>

          <Link href="/shop" className="bg-[#98a88a] text-white px-4 py-1.5 rounded-lg shadow-md hover:bg-[#88a77a] transition duration-300 transform hover:scale-105 flex items-center gap-2">
            <img src="/shopping-card.svg" alt="" className={"w-7"}/>
            Корзина
          </Link>
        </div>
      </div>
    </header>
    <main className={"flex-grow"}>
      {children}
    </main>
    <footer className="bg-[#333] text-white py-8">
      <div
        className="container mx-auto px-6 grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-8">
        <div>
          <h3 className="text-lg font-semibold mb-4">Контакты</h3>
          <p className="text-sm">Телефон: +7 123 456 789</p>
          <p className="text-sm">Email: info@cosmeticsstore.kz</p>
          <p className="text-sm">Адрес: ул. Примерная, 123, Алматы</p>
        </div>

        <div>
          <h3 className="text-lg font-semibold mb-4">Следите за нами</h3>
          <div className="flex space-x-4">
            <a href="https://www.instagram.com" className="text-[#ADBFAD] hover:text-white">
              Instagram
            </a>
            <a href="https://wa.me" className="text-[#ADBFAD] hover:text-white">
              WhatsApp
            </a>
            <a href="https://www.facebook.com" className="text-[#ADBFAD] hover:text-white">
              Facebook
            </a>
          </div>
        </div>

        <div>
          <h3 className="text-lg font-semibold mb-4">Полезные ссылки</h3>
          <ul>
            <li><a href="#" className="text-sm hover:text-[#ADBFAD]">Политика
              конфиденциальности</a></li>
            <li><a href="#" className="text-sm hover:text-[#ADBFAD]">Условия использования</a>
            </li>
            <li><a href="#" className="text-sm hover:text-[#ADBFAD]">О нас</a></li>
            <li><a href="#" className="text-sm hover:text-[#ADBFAD]">Доставка и оплата</a></li>
          </ul>
        </div>
      </div>

      <div className="text-center text-sm mt-8">
        <p>© 2024 Косметический магазин. Все права защищены.</p>
      </div>
    </footer>
    </body>
    </html>
  );
}
