import "./globals.css";
import {Link} from "@/src/common/Link";
import {Roboto} from 'next/font/google'
import classNames from "classnames";
import {Button, ButtonSizes} from "@/src/common/Button";

const montserrat = Roboto({
  weight: ["400", "700"],
  subsets: ["cyrillic"],
});


export const metadata = {
  title: "Suluskin - Магазин",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  return (
    <html lang="ru">
    <body
      className={classNames("flex flex-col min-h-screen", montserrat.className)}
    >
    <header className="bg-[#ADBFAD] py-5 fixed top-0 z-10 left-0 right-0">
      <div className="container mx-auto flex items-center justify-between">
        <Link href={"/"}>
          <img src="/logo.svg" alt="" className={"w-40 -translate-y-2"}/>
        </Link>

        <nav className="space-x-6">
          <Link href="/">Главная</Link>
          <Link href="/about">О нас</Link>
          <Link href="/delivery">Доставка</Link>
        </nav>

        <div className="flex items-center space-x-7">
          <a href="https://wa.me/1234567890"
             target="_blank">
            <img src="/wp.svg" alt=""
                 className={"w-8 transition duration-300 transform hover:scale-105"}/>
          </a>

          <a href="https://www.instagram.com/suluskin/"
             target="_blank">
            <img src="/instagram.svg" alt=""
                 className={"w-8 transition duration-300 transform hover:scale-105"}/>
          </a>
          <a href="https://www.instagram.com/suluskin/"
             target="_blank">
            <img src="/icons8-tiktok.svg" alt=""
                 className={"w-8 transition duration-300 transform hover:scale-105"}/>
          </a>
          <Button As={"link"} href={"/backet"} size={ButtonSizes.sm} className={"flex items-center gap-3"}>
            <img src="/shopping-card.svg" alt="" className={"w-7"}/>
            Корзина
          </Button>
        </div>
      </div>
    </header>
    <main className={"flex-grow mt-24"}>
      {children}
    </main>
    <footer className="bg-[#333] text-white py-8">
      <div
        className="container mx-auto px-6 grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-8">
        <div>
          <h3 className="text-lg font-semibold mb-4">Контакты</h3>
          <p className="text-sm mb-3">Телефон: +7 123 456 789</p>
          <p className="text-sm mb-3">Email: info@cosmeticsstore.kz</p>
          <p className="text-sm">Адрес: ул. Примерная, 123, Алматы</p>
        </div>

        <div>
          <h3 className="text-lg font-semibold mb-4">Следите за нами</h3>
          <div className="flex space-x-4">
            <a href="https://www.instagram.com/suluskin/" className="text-[#ADBFAD] hover:text-white">
              Instagram
            </a>
            <a href="https://wa.me" className="text-[#ADBFAD] hover:text-white">
              WhatsApp
            </a>
            <a href="https://wa.me" className="text-[#ADBFAD] hover:text-white">
              TikTok
            </a>
          </div>
        </div>
      </div>

      <div className="text-center text-sm mt-8">
        <p>© 2024 Косметический магазин. Все права защищены.</p>
      </div>
    </footer>
    </body>
    </html>
  );
}
